Modules:
  - TFminiPlus
  - UIServer
HardwareOptions:
  distanceDev:  "/dev/ttyUSB3"
  laneCam: "/dev/video0"
  signCam: "/dev/video2"
  obdDev: "/dev/ttyUSB4"
Thresholds:
  distanceTresholdSlow: 1.0
  distanceThresholdFast: 10.0
  distanceSlowThreshold: 50